# Generated by Django 4.2.9 on 2024-02-24 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uasams', '0002_alter_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='scholarshipName',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
