# Generated by Django 4.2.9 on 2024-05-07 02:05

from django.db import migrations, models
import uasams.models


class Migration(migrations.Migration):

    dependencies = [
        ('uasams', '0003_scholarship_scholarshipname'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='matchScore',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='meetsOtherRequirements',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('REJECTED', 'Rejected'), ('AWARDED', 'Awarded')], max_length=12),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[(uasams.models.UserType['STUDENT'], 'Student'), (uasams.models.UserType['SCHOLARSHIPADMIN'], 'Scholarship Administrator'), (uasams.models.UserType['APPLICANTREVIEWER'], 'Applicant Reviewer'), (uasams.models.UserType['SCHOLARSHIPPROVIDER'], 'Scholarship Provider'), (uasams.models.UserType['SCHOLARSHIPFUNDSTEWARD'], 'Scholarship Fund Steward'), (uasams.models.UserType['ENGINEERINGSTAFF'], 'Engineering Staff'), (uasams.models.UserType['ITSTAFF'], 'IT Staff')], max_length=25),
        ),
    ]
