from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('createuser/', views.create_user),
    path('getusers/', views.get_users),
    path('updateuser/', views.update_user),
    path('createapplication/', views.create_application),
    path('createstudent/', views.create_student),
    path('getallscholarships/', views.get_all_scholarships),
    path('login/', views.login),
    path('createscholarship/', views.create_scholarship),
    path('appmatch/', views.application_match),
    path('scholarships/<str:scholarship_id>/', views.update_scholarship, name='update_scholarship'),
    path('filter_scholarships_by_name/', views.filter_scholarships_by_name, name='name'),
    path('updateApplication/<int:application_id>', views.update_application, name='id'),
    path('applicants_for_scholarship/<int:id>/', views.applicants_for_scholarship, name='id'),
    path('open_scholarships/', views.open_scholarships),
    path('closed_scholarships/', views.closed_scholarships),
    path('get_deadlines/', views.get_deadlines),
    path('get_scholarship_providers/', views.get_scholarship_providers),
    path('awarded_scholarships/', views.get_awarded_scholarships),
    path('get_student_applications/', views.get_student_applications),
    path('get_scholarship_applications/', views.get_scholarship_applications),
    path('getapplications/', views.get_applications),
    path('getscholarshipsfromapplications/<str:application_ids>/', views.get_scholarships_from_applications),
    path('filter_applications/', views.filter_applications),
    path('filter_donors/', views.filter_donors),
    path('filter_applicants/', views.filter_applicants),
    path('applicantreport/', views.query_applicants),
    path('archived_scholarship_report/', views.archived_scholarship_report),
    path('available_scholarship_report/', views.available_scholarship_report),
    path('student_demographics_report/', views.student_demographics_report),
    path('updateStudent/', views.update_student),
    path('active_donor_report/', views.active_donor_report),
    path('scholarships/<int:scholarship_id>/delete/', views.delete_scholarship, name='delete_scholarship'),
    path('delete_user/', views.delete_user, name='delete_user'),
]
